run:
  timeout: 5m

output:
  format: github-actions

skip-files:
  - "*generated*.go$"

linters:
  disable-all: true
  enable:
  - errcheck
  - gofmt
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - thelper
  - unused
  fast: false
