run:
  timeout: 5m

output:
  format: github-actions

skip-files:
  - "*generated*.go$"

linters:
  disable-all: true
  enable:
  - errcheck
  - gofmt
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - thelper
  - unused
  - goimports
  - whitespace
  - revive
  fast: false
  max-same-issues: 50

linters-settings:
  revive:
    ignore-generated-header: false
    severity: warning
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true
