kind: APIService
apiVersion: apiregistration.k8s.io/v1
metadata:
  name: v1.api.acorn.io
spec:
  insecureSkipTLSVerify: true
  version: v1
  group: api.acorn.io
  service:
    namespace: acorn-system
    name: acorn-api
    port: 7443
  groupPriorityMinimum: 2000
  versionPriority: 10
---
kind: APIService
apiVersion: apiregistration.k8s.io/v1
metadata:
  name: v1.admin.acorn.io
spec:
  insecureSkipTLSVerify: true
  version: v1
  group: admin.acorn.io
  service:
    namespace: acorn-system
    name: acorn-api
    port: 7443
  groupPriorityMinimum: 2000
  versionPriority: 10
---
kind: Service
apiVersion: v1
metadata:
  name: acorn-api
  namespace: acorn-system
spec:
  selector:
    app: acorn-api
  ports:
    - port: 7443
      targetPort: 7443
      protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: acorn-api
  namespace: acorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acorn-api
  template:
    metadata:
      labels:
        app: acorn-api
    spec:
      containers:
        - name: acorn-api
          image: ghcr.io/acorn-io/acorn
          args:
            - api-server
          ports:
            - containerPort: 7443
          securityContext:
            runAsUser: 1000
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
      priorityClassName: system-cluster-critical
      serviceAccountName: acorn-system
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: "Exists"
---
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: acorn-api
  namespace: acorn-system
spec:
  maxUnavailable: 25%
  selector:
    matchLabels:
      app: acorn-api

