name: Try MacOS
on:
  push:
    paths-ignore:
      - docs/**
    branches:
      - main
  pull_request:
    paths-ignore:
      - docs/**
    branches:
      - main

jobs:
  try-macos:
    runs-on: macos-12-xl
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: true
          go-version: "1.20"
      - name: Install Docker CLI
        run: brew install docker
      - name: Start Colima # Starts the Docker Daemon without Docker Desktop
        run: colima start
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Keychain
        id: keychain
        uses: acorn-io/actions-setup-keychain@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v1.4.1"
      - name: Setup Cosign
        run: |
          echo "${COSIGN_KEY}" > "$GITHUB_WORKSPACE/cosign.key"
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
      - run: make validate-code