//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	internal_acorn_iov1 "github.com/acorn-io/acorn/pkg/apis/internal.acorn.io/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVolumeClassInstance) DeepCopyInto(out *ClusterVolumeClassInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.AllowedAccessModes != nil {
		in, out := &in.AllowedAccessModes, &out.AllowedAccessModes
		*out = make(internal_acorn_iov1.AccessModes, len(*in))
		copy(*out, *in)
	}
	out.Size = in.Size
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVolumeClassInstance.
func (in *ClusterVolumeClassInstance) DeepCopy() *ClusterVolumeClassInstance {
	if in == nil {
		return nil
	}
	out := new(ClusterVolumeClassInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterVolumeClassInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVolumeClassInstanceList) DeepCopyInto(out *ClusterVolumeClassInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterVolumeClassInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVolumeClassInstanceList.
func (in *ClusterVolumeClassInstanceList) DeepCopy() *ClusterVolumeClassInstanceList {
	if in == nil {
		return nil
	}
	out := new(ClusterVolumeClassInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterVolumeClassInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectVolumeClassInstance) DeepCopyInto(out *ProjectVolumeClassInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.AllowedAccessModes != nil {
		in, out := &in.AllowedAccessModes, &out.AllowedAccessModes
		*out = make(internal_acorn_iov1.AccessModes, len(*in))
		copy(*out, *in)
	}
	out.Size = in.Size
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectVolumeClassInstance.
func (in *ProjectVolumeClassInstance) DeepCopy() *ProjectVolumeClassInstance {
	if in == nil {
		return nil
	}
	out := new(ProjectVolumeClassInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectVolumeClassInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectVolumeClassInstanceList) DeepCopyInto(out *ProjectVolumeClassInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectVolumeClassInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectVolumeClassInstanceList.
func (in *ProjectVolumeClassInstanceList) DeepCopy() *ProjectVolumeClassInstanceList {
	if in == nil {
		return nil
	}
	out := new(ProjectVolumeClassInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectVolumeClassInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeClassSize) DeepCopyInto(out *VolumeClassSize) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeClassSize.
func (in *VolumeClassSize) DeepCopy() *VolumeClassSize {
	if in == nil {
		return nil
	}
	out := new(VolumeClassSize)
	in.DeepCopyInto(out)
	return out
}
